#!/bin/sh

BASE=`cd "\`dirname "\\\`readlink "$0" || echo $0\\\`"\`" && pwd`
ASSEMBLY=`find $BASE/bin -name tack.exe | xargs ls -t | head -1`

if [ -z $ASSEMBLY ]; then
  echo "Unable to find program. Correctly installed?" > /dev/stderr
  exit 1
fi

mono $ASSEMBLY $@
