#!/bin/sh

BASE=`cd "\`dirname "\\\`readlink "$0" || echo $0\\\`"\`" && pwd`

EXE=tack.exe
ASSEMBLY=
for i in $BASE/bin/Release/$EXE $BASE/bin/Debug/$EXE; do
  if [ -r $i ]; then
    ASSEMBLY=$i
    break
  fi
done

if [ -z $ASSEMBLY ]; then
  echo "Unable to find $EXE" > /dev/stderr
  exit 1
fi

mono $ASSEMBLY $@
